* Exoshell

A terminal proxy with sub-shell for programmatic controlling your via
Common-Lisp terminal. 

This is very much a work in progress -- Here be Dragons! 

** Getting Started 

*** Prerequisites

This project requires ECL (Embeddable Common-Lisp) which can be found at the
link below. 

- https://common-lisp.net/project/ecl/

*** Installing 

#+BEGIN_SRC sh
autoreconf -iv
./configure 
make 
sudo make install 
#+END_SRC

*** FAQ 

- Does this require Emacs. 

  No, Emacs is not required. But many parts of this project are modeled off of
  Emacs. 

- Why did you make this?

  See the "Why I made this" section below.

- What terminal can I use this? 

  Any xterm compatible terminal should work fine. Although some things have been
  tailored to Alacritty not fully implemented xterm implementation. Namely the
  lack of support for clearing a rectangular region. This may be emulated later. 


*** Why I made this

For the longest time I have wanted to be able to programmatic control my terminal
for various task. This is mostly because my carrear path has required me to log
into many differed systems not fully under my control, or as one offs. I often
thought it would be nice to be able to log my interactions with such systems,
and to be able to automate some of the more repetitive task without giving up
interactivity with the terminal as you do with things like expect scripts. The
solution for me was to have some way of reading exactly what is on the terminal
pragmatically and then reacting to what is on the screen with various code
snippets. 

*** Future features 

- Send and receive files from remote nested terminals.
- Parse JSON on display to gather information. 
- Line, word and character hooks. 
- Expect like handling of events on screen. 




